language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# database
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_script:
  - psql -c 'create database test_politico;' -U postgres
# command to run tests
script:
  - pytest --cov-config .coveragerc --cov=api/
after_success:
  - coveralls